language: objective-c
before_install:
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secrets.tar.enc -out secrets.tar -d
- brew tap caskroom/cask
- brew tap improbable-io/spatialos
- brew tap wooga/unityversions
- brew update
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- tar xvf secrets.tar
- mkdir ~/.m2
- mv settings.xml ~/.m2/settings.xml
- mkdir ~/.ivy2
- mv improbable.credentials ~/.ivy2/improbable.credentials
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
