language: objective-c
before_install:
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
