language: objective-c

cache:
  timeout: 1800
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
- brew update
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secret.enc -out secret -d
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh

install:
- "./Scripts/install.sh"
- spatial diagnose --log_level=debug

script:
- "./Scripts/build.sh"

after_script:
- curl --upload-file $TRAVIS_BUILD_DIR/logs/spatial.log https://transfer.sh/spatial_$TRAVIS_BUILD_NUMBER.log
- find / -type f -name .invoke.log
- curl --upload-file $TRAVIS_BUILD_DIR/workers/unity/.invoke.log https://transfer.sh/.invoke_$TRAVIS_BUILD_NUMBER.log
