language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- brew tap caskroom/cask
- brew tap improbable-io/spatialos
- brew tap wooga/unityversions
- brew update
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
