language: objective-c

env:
  global:
    - UNITY_VERSION=5.6.0
    - UNITY_FOLDER=/Applications/Unity
    - HOMEBREW_FOLDER=$HOME/Library/Caches/Homebrew
    - PROJECT_NAME=mysimplerpg
    - ASSEMPLY_NAME=$PROJECT_NAME$( date +%Y%m%d%H%M%S )

cache:
  timeout: 3600
  directories:
    - $UNITY_FOLDER

notifications:
  email:
    - andrea@dellacorte.me

before_install:
- brew update
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Script/secret.sh

install:
- "./Scripts/install.sh"

script:
- "./Scripts/secrets.sh"
- "./Scripts/build.sh"

after_script:
- curl --upload-file $TRAVIS_BUILD_DIR/logs/spatial.log https://transfer.sh/spatial_$TRAVIS_BUILD_NUMBER.log
