language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- brew update
- brew upgrade
install:
- ./Scripts/install.sh
script:
- ./Scripts/build.sh
