language: objective-c

env:
  global:
    - UNITY_VERSION=5.6.0
    - UNITY_FOLDER=/Applications/Unity
    - HOMEBREW_FOLDER=$HOME/Library/Caches/Homebrew

cache:
  timeout: 3600
  directories:
    - $UNITY_FOLDER

notifications:
  email:
    - andrea@dellacorte.me

before_install:
- brew update
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secret.enc -out secret -d
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh

install:
- "./Scripts/install.sh"

script:
- "./Scripts/build.sh"

after_script:
- curl --upload-file $TRAVIS_BUILD_DIR/logs/spatial.log https://transfer.sh/spatial_$TRAVIS_BUILD_NUMBER.log
