language: objective-c

env:
  global:
    - UNITY_VERSION=5.6.0
    - UNITY_FOLDER=/Applications/Unity
    - HOMEBREW_FOLDER=$HOME/Library/Caches/Homebrew
    - PROJECT_NAME=mysimplerpg
    - ASSEMBLY_NAME=mysimplerpg_$TRAVIS_BUILD_ID

cache:
  timeout: 3600
  directories:
    - $HOMEBREW_FOLDER

notifications:
  email:
    - andrea@dellacorte.me

before_install:
- brew update
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- chmod a+x ./Scripts/secret.sh
- chmod a+x ./Scripts/deploy.sh

install:
- ./Scripts/install.sh

script:
- ./Scripts/secret.sh
- if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./Scripts/build.sh; fi
- if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./Scripts/deploy.sh; fi

after_script:
- curl --upload-file $TRAVIS_BUILD_DIR/logs/spatial.log https://transfer.sh/spatial_$TRAVIS_BUILD_NUMBER.log
