language: objective-c
cache:
  timeout: 1800
  directories:
    - $HOME/Library/Caches/Homebrew
#  - /Applications/Unity-5.6.1f1
#  - /Applications/Unity
before_install:
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secret.enc -out secret -d
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
