language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- openssl aes-256-cbc -K $encrypted_3a211ca5956d_key -iv $encrypted_3a211ca5956d_iv
  -in secrets.tar.enc -out secrets.tar -d
- chmod a+x ./Scripts/install.sh
- chmod a+x ./Scripts/build.sh
- brew tap caskroom/cask
- brew tap improbable-io/spatialos
- brew tap wooga/unityversions
- brew update
install:
- "./Scripts/install.sh"
script:
- "./Scripts/build.sh"
